# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rake'
gem 'activerecord', "~>5.2.3"
gem 'sinatra-activerecord'
gem 'require_all'
gem 'pry'
gem 'unicode', '~> 0.4.4.2'
gem 'ruby2d', '~> 0.9.4'
gem 'tty-prompt'
gem 'colorize'